# Generated by Django 4.2.29 on 2026-04-04 21:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('technologies', models.CharField(max_length=300, verbose_name='Technologies utilisées')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True, verbose_name='Lien du projet')),
                ('github_url', models.URLField(blank=True)),
                ('date_created', models.DateField(verbose_name='Date de création')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet à la une')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-featured', 'order', '-date_created'],
            },
        ),
    ]
