# Generated by Django 4.2.29 on 2026-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('current', models.BooleanField(default=False, verbose_name='En cours')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Éducation',
                'verbose_name_plural': 'Éducations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
    ]
